$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
code: model
command: >-
    python train.py 
    --training_data diabetes-prod-folder           
    --reg_rate: 0.02
environment: azureml:AzureML-sklearn-0.24-ubuntu18.04-py37-cpu@latest
compute: azureml:mlops-github-action
description: "MLOpsexperiment"