name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v4

    - name: Install Azure CLI and ML extension
      run: |
        az extension add -n ml -y

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Submit Azure ML Job
      run: |
        az ml job create --file azureml/job-config.yml \
          --resource-group hydra-eu-rg \
          --workspace-name hydra-eu-ws
