name: Manually trigger an Azure Machine Learning job

on:
  push:
    branches:
      - main

jobs:
  experiment:
    runs-on: ubuntu-latest
    environment: 
          name: development  # Specify the production environment
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Install Azure CLI and ML extension
        run: |
          az extension add -n ml -y

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Submit Azure ML Job
        run: |
          az ml job create --file src/train-dev.yml \
            --resource-group hydra-eu-rg \
            --workspace-name hydra-eu-ws \
            --stream

  production:
    needs: experiment
    runs-on: ubuntu-latest
    environment: 
          name: production  # Specify the production environment
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Install Azure CLI and ML extension
        run: |
          az extension add -n ml -y

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Submit Azure ML Job
        run: |
          az ml job create --file src/train-prod.yml \
            --resource-group hydra-eu-rg \
            --workspace-name hydra-eu-ws \
            --stream
